export const politicSentence = [
  [
    'Caros eleitores, ',
    'Por outro lado, ',
    'Assim mesmo, ',
    'No entanto, não podemos esquecer que ',
    'Do mesmo modo, ',
    'A minha prática na política prova que ',
    'Nunca é demais lembrar o peso e o significado destes problemas, uma vez que ',
    'As minhas experiências acumuladas no meio político demonstram que ',
    'Acima de tudo, é fundamental ressaltar que ',
    'O incentivo ao avanço das políticas públicas, assim como ',
    'Não obstante, ',
    'Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se ',
    'Pensando mais a longo prazo, ',
    'O que temos que ter sempre em mente é que ',
    'Ainda assim, existem dúvidas a respeito de como ',
    'Gostaria de enfatizar que ',
    'Todavia, ',
    'A nível sociocultural, ',
    'O empenho em analisar ',
    'Percebemos, cada vez mais, que ',
    'No governo atual, ',
    'É importante questionar o quanto ',
    'Neste sentido, ',
    'Evidentemente, ',
    'Por conseguinte, ',
    'É claro que ',
    'Podemos já vislumbrar o modo pelo qual ',
    'Desta maneira, ',
    'O cuidado em identificar as demandas dos eleitores ',
    'A nossa liderança política que nos ajuda a lidar com ',
  ],
  [
    'a execução das metas do meu mandato ',
    'a complexidade dos estudos efetuados ',
    'a contínua implementação de obras ',
    'a estrutura atual de poder ',
    'o novo modelo de política aqui preconizado ',
    'o desenvolvimento contínuo de distintas formas de atuação ',
    'a constante divulgação das informações ',
    'a consolidação das políticas públicas ',
    'a consulta aos diversos militantes ',
    'o início da atividade geral de formação de atitudes ',
    'o desafiador cenário político atual ',
    'a mobilidade urbana ',
    'o fenômeno da participação social ',
    'a hegemonia do ambiente político ',
    'a expansão das metas para meu mandato ',
    'o aumento do diálogo entre os diferentes setores produtivos ',
    'a crescente influência da mídia ',
    'a necessidade de renovação no cenário político ',
    'a segurança, educação e saúde ',
    'o surgimento do emprego ',
    'a revolução dos costumes ',
    'o acompanhamento das vontades do povo ',
    'o comprometimento com meus eleitores ',
    'a determinação clara de objetivos ',
    'a adoção de políticas descentralizadoras ',
    'a valorização de fatores subjetivos ',
    'a percepção das dificuldades ',
    'o entendimento das metas propostas ',
    'o consenso sobre a necessidade de melhoria da saúde ',
    'o julgamento imparcial das eventualidades ',
  ],
  [
    'nos obriga à análise ',
    'cumpre um papel essencial na formulação ',
    'exige a precisão e a definição ',
    'auxilia a preparação e a composição ',
    'garante a contribuição de um grupo importante na determinação ',
    'assume importantes posições no estabelecimento ',
    'facilita a criação ',
    'obstaculiza a apreciação da importância ',
    'oferece uma interessante oportunidade para verificação ',
    'acarreta um processo de reformulação e modernização ',
    'pode nos levar a considerar a reestruturação ',
    'representa uma abertura para a melhoria ',
    'ainda não demonstrou convincentemente que vai participar na mudança ',
    'talvez venha a ressaltar a relatividade ',
    'prepara-nos para enfrentar situações atípicas decorrentes ',
    'maximiza as possibilidades por conta ',
    'desafia a capacidade de equalização ',
    'agrega valor ao estabelecimento ',
    'é uma das consequências ',
    'promove a alavancagem ',
    'não pode mais se dissociar ',
    'possibilita uma melhor visão global ',
    'estimula a padronização ',
    'aponta para a melhoria ',
    'faz parte de um processo político ',
    'causa impacto indireto na reavaliação ',
    'apresenta tendências no sentido de aprovar a manutenção ',
    'estende o alcance e a importância ',
    'deve passar por modificações independentemente ',
    'afeta positivamente a correta previsão ',
  ],
  [
    'das condições políticas e governamentais exigidas.',
    'das diretrizes de desenvolvimento para o futuro.',
    'do sistema de participação geral.',
    'das posturas dos órgãos dirigentes com relação às suas atribuições.',
    'das novas proposições.',
    'das direções preferenciais no sentido político.',
    'do sistema de formação de empregos que corresponde às necessidades.',
    'das condições inegavelmente apropriadas.',
    'dos índices pretendidos.',
    'das formas de ação.',
    'dos paradigmas socioculturais.',
    'dos relacionamentos verticais entre executivo e legislativo.',
    'do processo de comunicação como um todo.',
    'dos métodos utilizados na avaliação de resultados.',
    'de todos os recursos públicos envolvidos.',
    'dos níveis de motivação da sociedade.',
    'da gestão inovadora da qual fazemos parte.',
    'dos modos de operação convencionais.',
    'de alternativas às soluções ortodoxas.',
    'dos procedimentos normalmente adotados.',
    'dos conhecimentos estratégicos para atingir a excelência.',
    'do fluxo de informações.',
    'do levantamento das variáveis envolvidas.',
    'das diversas correntes de pensamento.',
    'do impacto na agilidade decisória.',
    'das regras de conduta normativas.',
    'do orçamento público.',
    'do retorno esperado a longo prazo.',
    'do investimento em saúde, educação e segurança.',
    'do remanejamento dos recursos necessários.',
  ],
];
